In [1]:
l1=[1,2,3,4,5]
l2=[4,5,6,7,8]
a=l1+l2
print(a)
print(type(a))

[1, 2, 3, 4, 5, 4, 5, 6, 7, 8]
<class 'list'>


In [2]:
import numpy as np
list1 = np.array([1, 2, 3, 4, 5])
print(list1)
# Accessing elements
print(list1[2])
# Slicing
print(list1[1:4])

[1 2 3 4 5]
3
[2 3 4]


In [3]:
import numpy as np
l1=[1,2,3,4]
l2=[6,7,8,9]
a=np.array(l1)
b=np.array(l2)
print(a+b)
print(type(a+b))

[ 7  9 11 13]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[1,3,4],[4,2,9],[1,2,3]]
c=np.array(a)
d=np.array(b)
print(c+d)
#multiplication
e=np.matmul(a,b)
print(e)
f=np.power(a,b)
print(f)
g=np.divide(a,b)
print(g)

[[ 2  5  7]
 [ 8  7 15]
 [ 8 10 12]]
[[ 12  13  31]
 [ 30  34  79]
 [ 48  55 127]]
[[       1        8       81]
 [     256       25 10077696]
 [       7       64      729]]
[[1.         0.66666667 0.75      ]
 [1.         2.5        0.66666667]
 [7.         4.         3.        ]]


In [6]:
app=[1,3,2,4]
s=np.sin(app)
print(s)
t=np.log(app)
print(t)
u=np.log2(app)
print(u)
v=np.exp(app)
print(v)

[ 0.84147098  0.14112001  0.90929743 -0.7568025 ]
[0.         1.09861229 0.69314718 1.38629436]
[0.        1.5849625 1.        2.       ]
[ 2.71828183 20.08553692  7.3890561  54.59815003]
